### ISSUE TITLE
E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Rezenders** [cagbal/cob_people_object_detection_tensorflow#50]
Hello,

I was running this package with tensorflow without cuda and cdnn instalation, it was working just fine. Then, I installed tensorflow-gpu, cuda and cdnn in order to train custom objects. Now, when I run I get this error:

```
[ERROR] [1589904870.498858, 19.552000]: bad callback: <bound method PeopleObjectDetectionNode.rgb_callback of <__main__.PeopleObjectDetectionNode object at 0x7fe3ea7b3d90>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/gus/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow.py", line 130, in rgb_callback
    self._detector.detect(cv_image)
  File "/home/gus/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow/detector.py", line 163, in detect
    feed_dict={image_tensor: np.expand_dims(image, 0)})
  File "/home/gus/.local/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/gus/.local/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/gus/.local/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/gus/.local/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node FeatureExtractor/MobilenetV2/Conv/Conv2D (defined at /.local/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Exit_8/_75]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node FeatureExtractor/MobilenetV2/Conv/Conv2D (defined at /.local/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for u'FeatureExtractor/MobilenetV2/Conv/Conv2D':
  File "/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow.py", line 160, in <module>
    main()
  File "/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow.py", line 157, in main
    node = PeopleObjectDetectionNode()
  File "/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow.py", line 39, in __init__
    num_workers)
  File "/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow/detector.py", line 66, in __init__
    self.prepare()
  File "/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow/detector.py", line 102, in prepare
    self.load_model()
  File "/Documents/git/jason_ros_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow/detector.py", line 83, in load_model
    tf.import_graph_def(od_graph_def, name='')
  File "/.local/lib/python2.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

I found the issues https://github.com/tensorflow/tensorflow/issues/24496 and https://github.com/tensorflow/tensorflow/issues/28254, in both the solution is to add `config.gpu_options.allow_growth = True`.

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```
 I added it in [detector.py](https://github.com/cagbal/ros_people_object_detection_tensorflow/blob/master/src/cob_people_object_detection_tensorflow/detector.py) but it didnt work.

```
if self._num_workers == -1:
            self._sess = tf.Session(graph=self._detection_graph)
        else:
            session_conf = tf.ConfigProto(
                intra_op_parallelism_threads=self._num_workers,
                inter_op_parallelism_threads=self._num_workers,
            )

            session_conf.gpu_options.allow_growth = True

            self._sess = tf.Session(graph=self._detection_graph,
                config=session_conf)

```

I tried uninstalling tensorflow-gpu and installing tensorflow:
```
pip uninstall tensorflow-gpu==1.15.0
pip install tensorflow==1.15.0
```

Any ideas on how to fix this?

EDIT:
As a workaround I uninstalled libcudnn and it works now without running on gpu

**Comment by cagbal** [comment]
Hi, I initially wrote this only for the CPU. That's why I haven't tried it on GPU, let me check it in a few days.
